// Shared mutable DOM reference object — populated by buildDomRefs() after partials are injected
export const dom = {};

export function buildDomRefs() {
  const $ = id => document.getElementById(id);

  Object.assign(dom, {
    titlebar:            $('titlebar'),
    btnCollapse:         $('btn-collapse'),
    btnClose:            $('btn-close'),
    tabs:                document.querySelectorAll('.tab'),
    tabPanels:           document.querySelectorAll('.tab-panel'),
    btnSettingsTab:      $('btn-settings-tab'),
    serverBtns:          document.querySelectorAll('.server-btn'),

    searchInput:         $('search-input'),
    searchAutocomplete:  $('search-autocomplete'),
    searchMajor:         $('search-major'),
    searchMinor:         $('search-minor'),
    searchQuality:       $('search-quality'),
    searchPlus:          $('search-plus'),
    searchPlusAny:       $('search-plus-any'),
    searchSockets:       $('search-sockets'),
    searchMaxPrice:      $('search-maxprice'),
    searchBtn:           $('search-btn'),
    searchClear:         $('search-clear'),
    searchClearListings: $('search-clear-listings'),
    searchResults:       $('search-results'),
    searchCount:         $('search-count'),
    priceLow:            $('price-low'),
    priceAvg:            $('price-avg'),
    priceHigh:           $('price-high'),
    minimapPopup:        $('minimap-popup'),
    minimapCanvas:       $('minimap-popup-canvas'),
    minimapCaption:      $('minimap-popup-caption'),

    historyItemName:     $('history-item-name'),
    historyAutocomplete: $('history-autocomplete'),
    historyMajor:        $('history-major'),
    historyMinor:        $('history-minor'),
    historyQuality:      $('history-quality'),
    historyPlus:         $('history-plus'),
    historySockets:      $('history-sockets'),
    historySearchBtn:    $('history-search-btn'),
    historyClear:        $('history-clear'),
    dayBtns:             document.querySelectorAll('.day-btn'),
    chartCanvas:         $('chart-canvas'),
    chartPlaceholder:    $('chart-placeholder'),
    histLow:             $('hist-low'),
    histMed:             $('hist-med'),
    histHigh:            $('hist-high'),

    watchItem:           $('watch-item'),
    watchAutocomplete:   $('watch-autocomplete'),
    watchMajor:          $('watch-major'),
    watchMinor:          $('watch-minor'),
    watchQuality:        $('watch-quality'),
    watchPlus:           $('watch-plus'),
    watchPlusAny:        $('watch-plus-any'),
    watchSockets:        $('watch-sockets'),
    watchInterval:       $('watch-interval'),
    watchPriceBasis:     $('watch-price-basis'),
    watchPricePct:       $('watch-price-pct'),
    watchUseHistoryBtn:  $('watch-use-history-btn'),
    watchPrice:          $('watch-price'),
    watchStartBtn:       $('watch-start-btn'),
    watchClear:          $('watch-clear'),
    watchClearListings:  $('watch-clear-listings'),
    watchDot:            $('watch-dot'),
    watchText:           $('watch-text'),
    watchMatches:        $('watch-matches'),

    themeSelect:         $('theme-select'),
    uiScaleSelect:       $('ui-scale-select'),
    fontPairingSelect:   $('font-pairing-select'),
    opacitySlider:       $('opacity-slider'),
    opacityInput:        $('opacity-input'),
    textOpacitySlider:   $('text-opacity-slider'),
    textOpacityInput:    $('text-opacity-input'),
    resetPositionBtn:    $('reset-position-btn'),
    automationProfile:   $('automation-profile-select'),
    automationProfileNew:$('automation-profile-new'),
    automationProfileDelete:$('automation-profile-delete'),
    automationProfileExport:$('automation-profile-export'),
    automationProfileImport:$('automation-profile-import'),
    automationHelperStatus:$('automation-helper-status'),
    automationTargetStatus:$('automation-target-status'),
    automationMasterStatus:$('automation-master-status'),
    automationLeftInterval:$('automation-left-interval'),
    automationRightInterval:$('automation-right-interval'),
    automationF7Interval: $('automation-f7-interval'),
    automationJitter:     $('automation-jitter'),
    automationSaveRuntime:$('automation-save-runtime'),
    automationProfileName:$('automation-profile-name'),
    automationProfileDescription:$('automation-profile-description'),
    automationTargetTitle:$('automation-target-title'),
    automationTargetMatchMode:$('automation-target-match-mode'),
    automationTargetProcessName:$('automation-target-process-name'),
    automationTargetRequireForeground:$('automation-target-require-foreground'),
    automationTargetPollInterval:$('automation-target-poll-interval'),
    automationSaveProfileTarget:$('automation-save-profile-target'),
    automationBuffStigmaLabel:$('automation-buff-stigma-label'),
    automationBuffStigmaDuration:$('automation-buff-stigma-duration'),
    automationBuffStigmaWarn1:$('automation-buff-stigma-warn1'),
    automationBuffStigmaWarn2:$('automation-buff-stigma-warn2'),
    automationBuffStigmaVisible:$('automation-buff-stigma-visible'),
    automationBuffShieldLabel:$('automation-buff-shield-label'),
    automationBuffShieldDuration:$('automation-buff-shield-duration'),
    automationBuffShieldWarn1:$('automation-buff-shield-warn1'),
    automationBuffShieldWarn2:$('automation-buff-shield-warn2'),
    automationBuffShieldVisible:$('automation-buff-shield-visible'),
    automationBuffInvisibilityLabel:$('automation-buff-invisibility-label'),
    automationBuffInvisibilityDuration:$('automation-buff-invisibility-duration'),
    automationBuffInvisibilityWarn1:$('automation-buff-invisibility-warn1'),
    automationBuffInvisibilityWarn2:$('automation-buff-invisibility-warn2'),
    automationBuffInvisibilityVisible:$('automation-buff-invisibility-visible'),
    automationSaveBuffs:$('automation-save-buffs'),
    automationHotkeyMaster:$('automation-hotkey-master'),
    automationHotkeyEmergency:$('automation-hotkey-emergency'),
    automationHotkeyLeft:$('automation-hotkey-left'),
    automationHotkeyRight:$('automation-hotkey-right'),
    automationHotkeyF7:$('automation-hotkey-f7'),
    automationHotkeyShift:$('automation-hotkey-shift'),
    automationHotkeyCtrl:$('automation-hotkey-ctrl'),
    automationHotkeyStigma:$('automation-hotkey-stigma'),
    automationHotkeyShield:$('automation-hotkey-shield'),
    automationHotkeyInvisibility:$('automation-hotkey-invisibility'),
    automationSaveHotkeys:$('automation-save-hotkeys'),
    automationHudEnabled: $('automation-hud-enabled'),
    automationBuffsEnabled:$('automation-buffs-enabled'),
    automationCompactHud:$('automation-compact-hud'),
    automationShowActiveBuffsOnly:$('automation-show-active-buffs-only'),
    automationHideHudUnfocused:$('automation-hide-hud-unfocused'),
    automationHideBuffsUnfocused:$('automation-hide-buffs-unfocused'),
    automationAnchorMode: $('automation-anchor-mode'),
    automationSaveOverlays:$('automation-save-overlays'),
    automationRefreshBtn:$('automation-refresh-btn'),
    automationRestartBtn:$('automation-restart-btn'),
    automationMasterBtn: $('automation-master-btn'),
    automationStopBtn:   $('automation-stop-btn'),
    automationToggleLeft:$('automation-toggle-left'),
    automationToggleRight:$('automation-toggle-right'),
    automationToggleF7:  $('automation-toggle-f7'),
    automationToggleShift:$('automation-toggle-shift'),
    automationToggleCtrl:$('automation-toggle-ctrl'),
    automationTestLeft:  $('automation-test-left'),
    automationTestRight: $('automation-test-right'),
    automationTestF7:    $('automation-test-f7'),
    automationTestRelease:$('automation-test-release'),
    automationCopyLog:   $('automation-copy-log'),
    automationLog:       $('automation-log'),
    automationBuffList:  $('automation-buff-list'),

    alertPopup:          $('alert-popup'),
    alertItemName:       $('alert-item-name'),
    alertSeller:         $('alert-seller'),
    alertPrice:          $('alert-price'),

    altIndicator:        $('alt-indicator'),
    altHint:             $('alt-hint'),
    statusText:          $('status-text'),
    statusDot:           $('status-dot'),

    automationFkeyCode:              $('automation-fkey-code'),
    automationBuffStigmaMode:        $('automation-buff-stigma-mode'),
    automationBuffShieldMode:        $('automation-buff-shield-mode'),
    automationBuffInvisibilityMode:  $('automation-buff-invisibility-mode'),
    filterRememberServer:            $('filter-remember-server'),
    chartExpandBtn:                  $('chart-expand-btn'),
    chartTooltip:                    $('chart-tooltip'),
    chartModal:                      $('chart-modal'),
    chartModalCanvas:                $('chart-modal-canvas'),
    chartModalClose:                 $('chart-modal-close'),
    appHotkeyInteract:               $('app-hotkey-interact'),
    appHotkeyCollapse:               $('app-hotkey-collapse'),
    appHotkeyHide:                   $('app-hotkey-hide'),
    appHotkeyQuit:                   $('app-hotkey-quit'),
    appSaveHotkeys:                  $('app-save-hotkeys'),
  });
}
