export const state = {
  activeTab:        'search',
  server:           '',
  historyDays:      7,
  watchCancel:      null,
  watchReset:       null,
  isCollapsed:      false,
  altHeld:          false,
  searchItems:      [],
  watchItems:       [],
  searchSort:       { key: 'Price', dir: 'asc' },
  watchSort:        { key: 'Price', dir: 'asc' },
  itemNamePool:     [],
  poolLoaded:       false,
  filterMetaLoaded: false,
  filterMeta:       null,
  mapImage:         null,
  minimapSide:      'right',
  minimapPinned:    null,
  automationState:  null,
  automationLog:    [],
  automationHelperLifecycle: '',
  automationHelperErrorCode: '',
  historyPoints:    [],
  chartPts:         null,
};
